export const TOGGLE_BOXED_LAYOUT = "TOGGLE_BOXED_LAYOUT";
export const TOGGLE_COLLAPSED_NAV = "TOGGLE_COLLAPSED_NAV";
export const TOGGLE_NAV_BEHIND = "TOGGLE_NAV_BEHIND";
export const TOGGLE_FIXED_HEADER = "TOGGLE_FIXED_HEADER";
export const CHANGE_SIDEBAR_WIDTH = "CHANGE_SIDEBAR_WIDTH";
export const CHANGE_COLOR_OPTION = "CHANGE_COLOR_OPTION";
export const CHANGE_THEME = "CHANGE_THEME";

// authentication

export const ACTION_LOGIN = "ACTION_LOGIN";
export const ACTION_LOGOUT = "ACTION_LOGOUT";
export const ACTION_UPDATE_AUTH = "ACTION_UPDATE_AUTH";
export const ACTION_SIGNUP = "ACTION_SIGNUP";

// app

export const ACTION_UPDATE_APP = "ACTION_UPDATE_APP";
export const ACTION_HANDLE_ERROR = "ACTION_HANDLE_ERROR";

// profile

export const ACTION_UPDATE_PROFILE = "ACTION_UPDATE_PROFILE";
export const ACTION_CREATE_PROFILE = "ACTION_CREATE_PROFILE";
export const ACTION_MODIFY_PROFILE = "ACTION_MODIFY_PROFILE";
export const ACTION_DELETE_PROFILE = "ACTION_DELETE_PROFILE";
export const ACTION_GET_PROFILE = "ACTION_GET_PROFILE";

// Classes

export const ACTION_LIST_CLASSES = "ACTION_LIST_CLASSES";
export const ACTION_CREATE_CLASS = "ACTION_CREATE_CLASS";
export const ACTION_DELETE_CLASS = "ACTION_DELETE_CLASS";
export const ACTION_GET_CLASS_DETAIL = "ACTION_GET_CLASS_DETAIL";
export const ACTION_GET_CLASS_MEMBER_DETAIL = "ACTION_GET_CLASS_MEMBER_DETAIL";
export const ACTION_UPDATE_CLASSES = "ACTION_UPDATE_CLASSES";
export const ACTION_UPDATE_GET_CLASS_DETAIL = "ACTION_UPDATE_GET_CLASS_DETAIL";

// Texts

export const ACTION_LIST_TEXTS = "ACTION_LIST_TEXTS";
export const ACTION_LIST_TEXT_STAT_ITEMS = "ACTION_LIST_TEXT_STAT_ITEMS";
export const ACTION_UPDATE_TEXTS = "ACTION_UPDATE_TEXTS";

// STUDY TEXT
export const ACTION_STUDY_TEXT = "ACTION_STUDY_TEXT";
export const ACTION_UPDATE_STUDY_TEXT = "ACTION_UPDATE_STUDY_TEXT";
export const ACTION_GET_TEXT_DETAIL = "ACTION_GET_TEXT_DETAIL";

// Books

export const ACTION_LIST_BOOKS = "ACTION_LIST_BOOKS";
export const ACTION_LIST_BOOK_TEXTS = "ACTION_LIST_BOOK_TEXTS";
export const ACTION_LIST_BOOKS_STAT_ITEMS = "ACTION_LIST_BOOKS_STAT_ITEMS";
export const ACTION_UPDATE_BOOKS = "ACTION_UPDATE_BOOKS";

// Store

export const ACTION_LIST_STORE_ITEMS = "ACTION_LIST_STORE_ITEMS";
export const ACTION_UPDATE_STORE_ITEMS = "ACTION_UPDATE_STORE_ITEMS";
export const ACTION_MERGE_STORE_ITEMS = "ACTION_MERGE_STORE_ITEMS";

// Dictionary

export const ACTION_UPDATE_DICTIONARY = "ACTION_UPDATE_DICTIONARY";
export const ACTION_GET_DICTIONARY_ENTRY_DATA =
  "ACTION_GET_DICTIONARY_ENTRY_DATA";
